GET http://localhost:8082/user/messages/allMessages/2
Accept: application/json

###
GET http://localhost:8082/user/messages/allMessages/1
Accept: application/json

###
###



###
GET http://localhost:8082/users/all
Accept: application/json

###
POST http://localhost:8082/users/insert
Content-Type: application/json

{
  "firstName" : "Hassan" ,
  "lastName" : "Rouhani",
  "phoneNumber" : ""
}


###
