POST http://localhost:8082/user/messages/insert
Content-Type: application/json

{
  "userId": 152 ,
  "messageId": "0db60edaae5a461980a2fde72a76a9e5"
}

###
GET http://localhost:8082/users/all
Accept: application/json

###
POST http://localhost:8082/users/insert
Content-Type: application/json

{
  "firstName" : "Ali" ,
  "lastName" : "Valizadeh",
  "phoneNumber" : "09375242935"
}


###
