server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id : MessageModule
          uri: http://localhost:8081/
          predicates:
            - Path=/messages/**
        - id: UserModule
          uri: http://localhost:8082/
          predicates:
            - Path=/**
        - id: ChatModule
          uri: http://localhost:8083/
          predicates:
            - Path=/**