PATCH http://localhost:8081/messages/update
Content-Type: application/json

{
  "id": "ce1ff25c66a04607bfa8ef1bce40822",
  "text" : "Salam"
}

###
GET http://localhost:8081/logs/all
Accept: application/json

###
GET http://localhost:8081/messages/ce1ff25c66a04607bfa8ef1bce4088
Accept: application/json

###
GET http://localhost:8081/messages/all
Accept: application/json

###
POST http://localhost:8081/messages/insert
Content-Type: application/json

{
  "text": "Hello, my name is ali."
}



###
