PATCH http://localhost:8081/messages/update
Content-Type: application/json

{
  "id": "3170466c2dbf4b5db0711cfafc917b84",
  "text" : "Salam"
}

###
GET http://localhost:8081/logs/all
Accept: application/json

###
GET http://localhost:8081/messages/24f03f4f2ee24002bd4f2b24ba3384c52321
Accept: application/json

###
GET http://localhost:8081/messages/all
Accept: application/json

###
POST http://localhost:8081/messages/insert
Content-Type: application/json

{
  "text": "Hello, my name is ali."
}



###
